name: web_test
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  animations: ^2.0.11
  any_link_preview: ^3.0.2
  async: ^2.11.0
  audio_waveforms: ^1.1.1
  audioplayers: ^6.1.0
  audioplayers_web: ^5.0.0
  auto_size_text: ^3.0.0
  brasil_fields: ^1.15.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.0
  cloud_functions: ^5.1.0
  diacritic: ^0.1.6
  dio: ^5.7.0
  dotted_border: ^2.1.0
  emoji_picker_flutter: ^3.1.0
  file_picker: ^8.0.7
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  firebase_storage: ^12.2.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.1.1
  #flutterflow_ui: ^0.3.1
  flutter_spinkit: ^5.2.1
  flutterflow_widgets: ^0.0.7
  font_awesome_flutter: ^10.8.0
  from_css_color: ^2.0.0
  getwidget: ^4.0.0
  go_router: ^14.6.0
  google_fonts: ^6.2.1
  grouped_list: ^6.0.0
  http: ^1.2.2
  icons_plus: ^5.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_path: ^0.7.4
  loader_overlay: ^4.0.3
  open_file: ^3.5.4
  page_transition: ^2.1.0
  path: ^1.9.0
  path_provider: ^2.1.5
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  provider: ^6.1.2
  record: ^5.2.0
  record_platform_interface: ^1.2.0
  refresh_loadmore: ^2.0.7
  sqflite: ^2.4.1
  timeago: ^3.7.0
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  validadores: ^1.0.9
  video_player: ^2.9.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/facebook_icon.png
    - assets/images/google_icon.png
    - assets/images/logoTeste.png
