// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO39iRJsfjx2Xt3VCb4MFEloG10fO2Gas',
    appId: '1:390113074845:web:393df32a7cf839ca69fe74',
    messagingSenderId: '390113074845',
    projectId: 'hanuman-4e9f4',
    authDomain: 'hanuman-4e9f4.firebaseapp.com',
    storageBucket: 'hanuman-4e9f4.appspot.com',
    measurementId: 'G-5545S7G722',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAULQ94ulWeeuq9_JZXAuc1TVzfXU_u4Mo',
    appId: '1:390113074845:ios:a9e346b59ab20eba69fe74',
    messagingSenderId: '390113074845',
    projectId: 'hanuman-4e9f4',
    storageBucket: 'hanuman-4e9f4.appspot.com',
    iosBundleId: 'com.example.webTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO39iRJsfjx2Xt3VCb4MFEloG10fO2Gas',
    appId: '1:390113074845:web:393df32a7cf839ca69fe74',
    messagingSenderId: '390113074845',
    projectId: 'hanuman-4e9f4',
    authDomain: 'hanuman-4e9f4.firebaseapp.com',
    storageBucket: 'hanuman-4e9f4.appspot.com',
    measurementId: 'G-5545S7G722',
  );
}